[package]
name = "lagoon"
version = "0.1.0"
authors = ["Cooper b. Anderson <andersc7@rose-hulman.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
